### ISSUE TITLE
localStorage to php

### ISSUE THREAD

**Issue by basbroens** [Asraf-Uddin-Ahmed/jquery.mycart#8]
Hi,

I really like this plugin, but i can't seem to send the localStorage contents to php.

I'm trying to loop trough the shopping basket items and send the information through Ajax. However.. the localStorage.length is always 1 (no matter how many items i inserted in the shopping basket).

Does anyone have any idea to send the selected items to the server side?

**Comment by Veilleuse-00** [comment]
Hi!
I'm really interested about this subject too (sorry basbroens, I haven't got the solution).
I'm actually searching around "checkout cart' function, in order to make it send all informations on a php form page rather than opening an alert message containing them but still can't manage it.
Any help would be appreciated. 
Thanks in advance.

Edited 3 hours later .... :
For basbroens : localStorage.length is 1 because it's got only one data : products. But "products" is an array, so you have to iterate in it to get all your products data with "localStorage.products".
(If you look at the code, you'll see that Products manager handles those functions.)
Hope this helps.
